# Generated by Django 5.0.6 on 2026-09-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveBigIntegerField()),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(max_length=200)),
                ('item_unit_code', models.CharField(blank=True, default='', max_length=16)),
                ('uom_code', models.CharField(blank=True, default='', max_length=16)),
                ('color_id', models.PositiveBigIntegerField(blank=True, help_text='blank = all colors', null=True)),
                ('color_code', models.CharField(blank=True, default='', max_length=32)),
                ('color_name', models.CharField(blank=True, default='', max_length=100)),
                ('size_id', models.PositiveBigIntegerField(blank=True, help_text='blank = all sizes', null=True)),
                ('size_code', models.CharField(blank=True, default='', max_length=32)),
                ('size_name', models.CharField(blank=True, default='', max_length=100)),
                ('consumption', models.DecimalField(decimal_places=4, help_text='consumption per piece', max_digits=14)),
                ('wastage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supplier_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, help_text='optional', max_digits=18)),
                ('remark', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('deleted_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('style_id', models.PositiveBigIntegerField()),
                ('style_no', models.CharField(max_length=32)),
                ('style_name', models.CharField(blank=True, default='', max_length=200)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=16)),
                ('approved_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='bom_bom_status_379e59_idx'), models.Index(fields=['style_id'], name='bom_bom_style_i_83273f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('style_id', 'version_no'), name='uniq_bom_version'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bom'),
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['bom', 'item_id'], name='bom_bomitem_bom_id_816dee_idx'),
        ),
    ]
