# Generated by Django 5.0.6 on 2026-09-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims & Packaging'), ('cm', 'Cut & Make'), ('embroidery', 'Embroidery'), ('print', 'Print'), ('wash', 'Wash'), ('overhead', 'Overhead'), ('commission', 'Commission'), ('freight', 'Freight'), ('other', 'Other')], default='other', max_length=24)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('item_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=32)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('uom_code', models.CharField(blank=True, default='', max_length=16)),
                ('consumption', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, default=0, help_text='consumption × unit_cost', max_digits=18)),
                ('remark', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('deleted_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('style_id', models.PositiveBigIntegerField()),
                ('style_no', models.CharField(max_length=32)),
                ('style_name', models.CharField(blank=True, default='', max_length=200)),
                ('order_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order_no', models.CharField(blank=True, default='', max_length=32)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=16)),
                ('currency_id', models.PositiveBigIntegerField()),
                ('currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='1 currency = N base, captured at approval', max_digits=18, null=True)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('buyer_price', models.DecimalField(blank=True, decimal_places=4, help_text="buyer's confirmed unit price, for comparison", max_digits=18, null=True)),
                ('cost_per_piece', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fob_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('approved_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='costing_cos_status_27fa0b_idx'), models.Index(fields=['style_id'], name='costing_cos_style_i_156eaa_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='costing',
            constraint=models.UniqueConstraint(fields=('style_id', 'order_id', 'version_no'), name='uniq_costing_version'),
        ),
        migrations.AddField(
            model_name='costingline',
            name='costing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costing.costing'),
        ),
        migrations.AddField(
            model_name='costingline',
            name='root',
            field=models.ForeignKey(blank=True, help_text='line this version was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_lines', to='costing.costingline'),
        ),
    ]
