# Generated by Django 5.0.6 on 2026-09-24 11:45

import common.files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('deleted_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('sample_no', models.CharField(max_length=32, unique=True)),
                ('style_id', models.PositiveBigIntegerField()),
                ('style_no', models.CharField(max_length=32)),
                ('style_name', models.CharField(blank=True, default='', max_length=200)),
                ('sample_type', models.CharField(choices=[('proto', 'Proto'), ('fit', 'Fit'), ('size_set', 'Size Set'), ('pp', 'PP'), ('top', 'TOP'), ('salesman', 'Salesman')], default='proto', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('buyer_comments', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmit')], default='requested', max_length=16)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='samples_sam_status_c16975_idx'), models.Index(fields=['due_date'], name='samples_sam_due_dat_9a57e7_idx'), models.Index(fields=['style_id'], name='samples_sam_style_i_a1b641_idx')],
            },
        ),
        migrations.CreateModel(
            name='SampleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status_change_to', models.CharField(blank=True, default='', max_length=16)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='samples.samplerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=common.files.UploadToPath('samples'))),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='samples.samplerequest')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
