# Generated by Django 5.0.6 on 2026-09-24 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('deleted_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('order_no', models.CharField(max_length=32, unique=True)),
                ('buyer_po_no', models.CharField(max_length=100)),
                ('buyer_id', models.PositiveBigIntegerField()),
                ('buyer_code', models.CharField(blank=True, default='', max_length=32)),
                ('buyer_name', models.CharField(max_length=200)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('currency_id', models.PositiveBigIntegerField()),
                ('currency_code', models.CharField(blank=True, default='', max_length=8)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=200)),
                ('merchandiser_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('merchandiser_name', models.CharField(blank=True, default='', max_length=200)),
                ('excess_allowance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('short_allowance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('total_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['ship_date'], name='orders_orde_ship_da_a1b57e_idx'), models.Index(fields=['order_date'], name='orders_orde_order_d_d71205_idx'), models.Index(fields=['buyer_id'], name='orders_orde_buyer_i_90aa29_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('changed_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='orders.order')),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.PositiveBigIntegerField()),
                ('style_no', models.CharField(max_length=32)),
                ('style_name', models.CharField(blank=True, default='', max_length=200)),
                ('color_id', models.PositiveBigIntegerField()),
                ('color_code', models.CharField(blank=True, default='', max_length=32)),
                ('color_name', models.CharField(blank=True, default='', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.PositiveBigIntegerField()),
                ('size_code', models.CharField(blank=True, default='', max_length=32)),
                ('size_name', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='orders.orderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'style_id', 'color_id'), name='uniq_order_line'),
        ),
        migrations.AddConstraint(
            model_name='orderlinesize',
            constraint=models.UniqueConstraint(fields=('line', 'size_id'), name='uniq_order_line_size'),
        ),
    ]
