# Generated by Django 5.0.6 on 2026-09-24 11:45

import common.files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.PositiveBigIntegerField(blank=True, help_text='AMS user id', null=True)),
                ('deleted_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('style_no', models.CharField(max_length=32, unique=True)),
                ('buyer_id', models.PositiveBigIntegerField()),
                ('buyer_code', models.CharField(blank=True, default='', max_length=32)),
                ('buyer_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('trouser', 'Trouser'), ('t-shirt', 'T-Shirt'), ('jacket', 'Jacket'), ('shorts', 'Shorts'), ('polo', 'Polo'), ('kids', 'Kids'), ('other', 'Other')], default='other', max_length=16)),
                ('season', models.CharField(blank=True, default='', max_length=64)),
                ('fabric_type', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sample_approved', 'Sample Approved'), ('in_production', 'In Production'), ('discontinued', 'Discontinued')], default='draft', max_length=24)),
                ('version_no', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['buyer_id'], name='styles_styl_buyer_i_9f227d_idx'), models.Index(fields=['status'], name='styles_styl_status_55e89a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=common.files.UploadToPath('styles'))),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='styles.style')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StyleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('changed_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='styles.style')),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='styleversion',
            constraint=models.UniqueConstraint(fields=('style', 'version_no'), name='uniq_style_version'),
        ),
    ]
